apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cnpg-database
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: cnpg-operator
    - name: namespace  # Namespace created by flicknote-deploy (parallel with flicknote-infra)
    - name: secrets
  sourceRef:
    kind: GitRepository
    name: cloudnative-supabase
    namespace: flux-system
  path: ./flux/database/base
  prune: true
  # wait: true  # rely on healthChecks
  timeout: 5m
  patches:
    - target:
        kind: HelmRelease
        name: cnpg-cluster
      patch: |
        - op: replace
          path: /metadata/namespace
          value: flicknote-infra
        # OpenMeter role
        - op: add
          path: /spec/values/additionalRoles/-
          value:
            name: openmeter
            ensure: present
            login: true
            createdb: true
            passwordSecret:
              name: cnpg-openmeter-password
        # OpenMeter database
        - op: add
          path: /spec/values/additionalDatabases/-
          value:
            name: openmeter
            owner: openmeter
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: cnpg-cluster
      namespace: flicknote-infra
    - apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      name: supabase-pg
      namespace: flicknote-infra
