apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cnpg-operator
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: cnpg-sources
  sourceRef:
    kind: GitRepository
    name: cloudnative-supabase
    namespace: flux-system
  path: ./flux/infrastructure
  prune: true
  # wait: true  # rely on healthChecks
  timeout: 5m
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: cnpg
      namespace: cnpg-system
