apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cnpg-sources
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: sources
  sourceRef:
    kind: GitRepository
    name: cloudnative-supabase
    namespace: flux-system
  path: ./flux/sources
  prune: true
