apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: supabase
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: cnpg-database
    - name: secrets  # Needs secrets synced to supabase-dev via Reflector
  sourceRef:
    kind: GitRepository
    name: cloudnative-supabase
    namespace: flux-system
  path: ./flux/supabase/base
  prune: true
  # wait: true  # rely on healthChecks
  timeout: 5m
  patches:
    - target:
        kind: HelmRelease
        name: supabase
      patch: |
        - op: replace
          path: /metadata/namespace
          value: supabase-dev
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: supabase
      namespace: supabase-dev
