apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: supabase-pg
  namespace: PLACEHOLDER
spec:
  instances: 1
  imageName: ghcr.io/guionai/postgres-pgjwt:16.4

  enableSuperuserAccess: false

  # CNPG manages its own self-signed TLS certificates

  postgresql:
    # pg_stat_statements requires preloading to collect statistics
    shared_preload_libraries:
      - pg_stat_statements
    parameters:
      # Logical replication for CDC tools
      wal_level: logical
      max_replication_slots: "10"
      max_wal_senders: "10"
      # Performance
      shared_buffers: "256MB"
      log_min_messages: fatal
    # pg_hba: internal no SSL, external requires SSL
    pg_hba:
      # Local connections (CNPG manages this internally)
      - local all all trust
      # K3s pod CIDR - no SSL required
      - host all all 10.42.0.0/16 scram-sha-256
      # K3s service CIDR - no SSL required
      - host all all 10.43.0.0/16 scram-sha-256
      # External traffic - require SSL
      - hostssl all all 0.0.0.0/0 scram-sha-256
      # Reject non-SSL external connections
      - hostnossl all all 0.0.0.0/0 reject

  storage:
    size: 10Gi
    storageClass: local-path

  # Note: Database is created by CNPG Database CRD (consumers create their own)
  # Note: Roles are managed by managed.roles section
  # Note: Consumers can add additional roles via Kustomization patches

  # Managed services and roles
  managed:
    # LoadBalancer for external access (SSL required via pg_hba)
    services:
      additional:
        - selectorType: rw
          serviceTemplate:
            metadata:
              name: supabase-pg-lb
            spec:
              type: LoadBalancer

    roles:
      # === Supabase Core Roles ===
      # Non-login roles (for RLS policies)
      - name: anon
        ensure: present
        login: false
        inherit: false

      - name: authenticated
        ensure: present
        login: false
        inherit: false

      - name: service_role
        ensure: present
        login: false
        inherit: false
        bypassrls: true

      # Supabase admin (owns schemas, manages database)
      - name: supabase_admin
        ensure: present
        login: true
        createdb: true
        createrole: true
        bypassrls: true
        passwordSecret:
          name: cnpg-supabase-admin-password

      # Authenticator (PostgREST switches to anon/authenticated/service_role)
      - name: authenticator
        ensure: present
        login: true
        inherit: false
        passwordSecret:
          name: cnpg-authenticator-password
        inRoles:
          - anon
          - authenticated
          - service_role

      # Auth service admin
      - name: supabase_auth_admin
        ensure: present
        login: true
        inherit: false
        createrole: true
        passwordSecret:
          name: cnpg-supabase-auth-password

      # Storage service admin
      - name: supabase_storage_admin
        ensure: present
        login: true
        inherit: false
        createrole: true
        passwordSecret:
          name: cnpg-supabase-storage-password

      # Realtime service admin
      - name: supabase_realtime_admin
        ensure: present
        login: true
        inherit: false
        passwordSecret:
          name: cnpg-supabase-realtime-password

      # PgBouncer (connection pooling)
      - name: pgbouncer
        ensure: present
        login: true
        inherit: false
        passwordSecret:
          name: cnpg-pgbouncer-password
