apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: supabase-db
  namespace: PLACEHOLDER
spec:
  name: supabase
  owner: supabase_admin
  cluster:
    name: supabase-pg
  extensions:
    - name: uuid-ossp
      ensure: present
    - name: pgcrypto
      ensure: present
    - name: pg_stat_statements
      ensure: present
    - name: pgjwt
      ensure: present
  schemas:
    - name: auth
      owner: supabase_auth_admin
    - name: storage
      owner: supabase_storage_admin
    - name: extensions
      owner: supabase_admin
    - name: _analytics
      owner: supabase_admin
    - name: _realtime
      owner: supabase_realtime_admin
