---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: database
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: cnpg-operator
    - name: secrets
  sourceRef:
    kind: GitRepository
    name: cloudnative-supabase
  path: ./flux/database/example
  prune: true
  healthChecks:
    - apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      name: supabase-pg
      namespace: supabase
