---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: database
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: infrastructure
    - name: namespace
    - name: secrets
  sourceRef:
    kind: GitRepository
    name: cloudnative-supabase
  path: ./flux/database/example
  prune: true
  wait: true
  timeout: 10m
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: cnpg-cluster
      namespace: supabase
    - apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      name: supabase-pg
      namespace: supabase
