---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: namespace
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: cloudnative-supabase
  path: ./flux/namespace/example
  prune: false  # Don't delete namespace on removal
  healthChecks:
    - apiVersion: v1
      kind: Namespace
      name: supabase
