---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: secrets
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: namespace
  sourceRef:
    kind: GitRepository
    name: cloudnative-supabase
  path: ./flux/secrets/example
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
