apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg
  namespace: cnpg-system
spec:
  interval: 30m
  releaseName: cnpg
  chart:
    spec:
      chart: cloudnative-pg
      version: "0.26.1"
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
